name: Ruby
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    strategy:
      matrix:
        ruby:
          - "3.2.2"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run test cases
        run: bundle exec rake
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
